// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY0Xc9wCIUZJsC_ob-odj1_uOapD6MQT8',
    appId: '1:401164869188:web:5927cf6dbdd67899a2e611',
    messagingSenderId: '401164869188',
    projectId: 'warlocks-of-the-beach',
    authDomain: 'warlocks-of-the-beach.firebaseapp.com',
    storageBucket: 'warlocks-of-the-beach.firebasestorage.app',
    measurementId: 'G-273PMG2GCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwI9DDOyU0L3MhA3DK_hGr07VL-tb-tE4',
    appId: '1:401164869188:android:c5daecc5d0a5da25a2e611',
    messagingSenderId: '401164869188',
    projectId: 'warlocks-of-the-beach',
    storageBucket: 'warlocks-of-the-beach.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdtc38Ct0dIFoMJWbdWkDTdqf4AW52SDQ',
    appId: '1:401164869188:ios:aeca72b1d3dd6f73a2e611',
    messagingSenderId: '401164869188',
    projectId: 'warlocks-of-the-beach',
    storageBucket: 'warlocks-of-the-beach.firebasestorage.app',
    iosBundleId: 'com.example.dndApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdtc38Ct0dIFoMJWbdWkDTdqf4AW52SDQ',
    appId: '1:401164869188:ios:aeca72b1d3dd6f73a2e611',
    messagingSenderId: '401164869188',
    projectId: 'warlocks-of-the-beach',
    storageBucket: 'warlocks-of-the-beach.firebasestorage.app',
    iosBundleId: 'com.example.dndApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY0Xc9wCIUZJsC_ob-odj1_uOapD6MQT8',
    appId: '1:401164869188:web:00076e12c4f374efa2e611',
    messagingSenderId: '401164869188',
    projectId: 'warlocks-of-the-beach',
    authDomain: 'warlocks-of-the-beach.firebaseapp.com',
    storageBucket: 'warlocks-of-the-beach.firebasestorage.app',
    measurementId: 'G-4E00NK1D25',
  );
}
