// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJGhUtJmlCAMPtrIaSdrlYzY9MdhHa4Os',
    appId: '1:335669107426:web:06c98f35ff28bd02379cbb',
    messagingSenderId: '335669107426',
    projectId: 'dungeonsdragonscharcreator',
    authDomain: 'dungeonsdragonscharcreator.firebaseapp.com',
    storageBucket: 'dungeonsdragonscharcreator.firebasestorage.app',
    measurementId: 'G-CNS8FM2MN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeEeszkNd58qJGzMBQFe8lyoCkdm9Em8I',
    appId: '1:335669107426:android:01cfca8fc606a381379cbb',
    messagingSenderId: '335669107426',
    projectId: 'dungeonsdragonscharcreator',
    storageBucket: 'dungeonsdragonscharcreator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWzLs07Dc3e40MUd93OKVa8CnlH7U98Xg',
    appId: '1:335669107426:ios:e394459800c91dea379cbb',
    messagingSenderId: '335669107426',
    projectId: 'dungeonsdragonscharcreator',
    storageBucket: 'dungeonsdragonscharcreator.firebasestorage.app',
    iosBundleId: 'com.example.dndCharacterCreator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWzLs07Dc3e40MUd93OKVa8CnlH7U98Xg',
    appId: '1:335669107426:ios:e394459800c91dea379cbb',
    messagingSenderId: '335669107426',
    projectId: 'dungeonsdragonscharcreator',
    storageBucket: 'dungeonsdragonscharcreator.firebasestorage.app',
    iosBundleId: 'com.example.dndCharacterCreator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJGhUtJmlCAMPtrIaSdrlYzY9MdhHa4Os',
    appId: '1:335669107426:web:cd05a88d6f7642fa379cbb',
    messagingSenderId: '335669107426',
    projectId: 'dungeonsdragonscharcreator',
    authDomain: 'dungeonsdragonscharcreator.firebaseapp.com',
    storageBucket: 'dungeonsdragonscharcreator.firebasestorage.app',
    measurementId: 'G-YGPDJV1GSC',
  );
}